version: '3.8'
services:
  ping:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ping
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURSE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURSE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURSE_PASSWORD}
  postgres:
    env_file:
      - .env
    image: 'postgres:14.5-bullseye'
    restart: always
    container_name: postgresForTestTask
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATASOURSE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURSE_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: