version: '3.3'
services:
  app:
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: 'postgres:14.5-bullseye'
    restart: always
    container_name: postgresForTestTask
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATASOURSE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURSE_PASSWORD}
      - POSTGRES_DB=${DATASOURSE_DB_NAME}